name: segment_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Use 3.10 for max stability with TF 2.10
  - numpy
  - scipy
  - tifffile
  - joblib
  - matplotlib
  - scikit-image
  - imageio
  - pip
  - pip:
    # Use tensorflow-cpu to be explicit, and pin to 2.10.0 for stability
    - tensorflow-cpu==2.10.0 
    - keras 
    - keras-hub
    - tensorflow-hub 
    - imageio-ffmpeg
    - tqdm