name: segment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - tifffile
  - joblib
  - matplotlib
  - scikit-image
  - imageio
  - pip
  - pip:
    - tensorflow[and-cuda]
    - tensorflow-text
    - keras
    - keras-hub
    - imageio-ffmpeg
    - tqdm